#!/bin/sh
########################################################################################################################
# Updates all apt packages.
#
# Usage: /bin/sh aptup
########################################################################################################################

command -v apt > /dev/null 2>&1 || { echo 'ERROR: Program not found: apt' 1>&2; exit 1; }
[ "$(id -u)" -ne 0 ] && { echo 'ERROR: Must be run as root' 1>&2; exit 1; }

apt update -y
apt full-upgrade -y
apt autoclean -y
apt autoremove -y
