#!/bin/sh
########################################################################################################################
# Updates all pip3 packages.
#
# Usage: /bin/sh pipup
########################################################################################################################

command -v pip3 > /dev/null 2>&1 || { echo 'ERROR: Program not found: pip3' 1>&2; exit 1; }
pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install --upgrade
